2025-01-17 01:31:19,199 - INFO - Finished! Total sfe time: 10.359071254730225 
2025-01-17 01:31:19,199 - DEBUG - 909,server, Parsed server ram usage: 80704
2025-01-17 01:31:19,199 - DEBUG - 909,client, Parsed client ram usage: 80968
2025-01-17 01:31:41,181 - DEBUG - client all values : ['modprobe cpufreq_stats failedLoaded 0 prior measurements', 'RAPL device for cpu 0', 'RAPL device for cpu 0', 'Devfreq not enabled', 'glob returned GLOB_ABORTED', 'Preparing to take measurements', 'Taking 1 measurement(s) for a duration of 11 second(s) each.', '2024-12-19 05:29:05,987 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.1.1:61002', '2024-12-19 05:29:05,990 - tno.mpc.communication.httphandlers - ERROR - Message not received.', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1061, in _wrap_create_connection', '    sock = await aiohappyeyeballs.start_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 103, in start_connection', '    raise first_exception', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 81, in start_connection', '    sock = await _connect_sock(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 165, in _connect_sock', '    await loop.sock_connect(sock, address)', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect', '    return await fut', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb', "    raise OSError(err, f'Connect call failed {address}')", "ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.2', 61001)", '', 'The above exception was the direct cause of the following exception:', '', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/tno/mpc/communication/httphandlers.py", line 193, in _send', '    async with self.session.post(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1355, in __aenter__', '    self._resp: _RetType = await self._coro', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 659, in _request', '    conn = await self._connector.connect(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 557, in connect', '    proto = await self._create_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1002, in _create_connection', '    _, proto = await self._create_direct_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1336, in _create_direct_connection', '    raise last_exc', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1305, in _create_direct_connection', '    transp, proto = await self._wrap_create_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1076, in _wrap_create_connection', '    raise client_error(req.connection_key, exc) from exc', "aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.2:61001 ssl:default [Connect call failed ('192.168.1.2', 61001)]", '2024-12-19 05:29:07,056 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', '2024-12-19 05:29:07,088 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', '2024-12-19 05:29:07,175 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', '2024-12-19 05:29:07,225 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', 'TP is  0.001', '2024-12-19 05:29:07,242 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', '2024-12-19 05:29:07,264 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-12-19 05:29:07,266 - tno.mpc.communication.httphandlers - INFO - Server 192.168.1.1:61002 shutdown', 'Total bytes received: 1930', 'Total messages received: 5', '2024-12-19 05:29:07,270 - tno.mpc.communication.httphandlers - INFO - Client 192.168.1.2:61001 shutdown', 'Total bytes sent: 766', 'Total messages sent: 5', '2024-12-19 05:29:07,271 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 766', 'Total messages sent: 5', 'Total bytes received: 1930', 'Total messages received: 5', '\tCommand being timed: "python3.9 server_energy.py 1 909"', '\tUser time (seconds): 6.71', '\tSystem time (seconds): 0.82', '\tPercent of CPU this job got: 87%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.65', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80836', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 16072', '\tVoluntary context switches: 66', '\tInvoluntary context switches: 140', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0', 'PowerTOP outputing using base filename log/powertop_rpi_2025-01-17_01-31-08.csv']
2025-01-17 01:31:41,182 - DEBUG - server all values : ['modprobe cpufreq_stats failedLoaded 0 prior measurements', 'RAPL device for cpu 0', 'RAPL device for cpu 0', 'Devfreq not enabled', 'glob returned GLOB_ABORTED', 'Preparing to take measurements', 'Taking 1 measurement(s) for a duration of 11 second(s) each.', '2024-12-19 05:29:43,448 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.1.2:61001', '2024-12-19 05:29:44,433 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', '2024-12-19 05:29:44,546 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', '2024-12-19 05:29:44,573 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', '2024-12-19 05:29:44,622 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', 'TP is  0.001', '2024-12-19 05:29:44,669 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', '2024-12-19 05:29:44,674 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-12-19 05:29:44,675 - tno.mpc.communication.httphandlers - INFO - Server 192.168.1.2:61001 shutdown', 'Total bytes received: 766', 'Total messages received: 5', '2024-12-19 05:29:44,678 - tno.mpc.communication.httphandlers - INFO - Client 192.168.1.1:61002 shutdown', 'Total bytes sent: 1930', 'Total messages sent: 5', '2024-12-19 05:29:44,679 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 1930', 'Total messages sent: 5', 'Total bytes received: 766', 'Total messages received: 5', '\tCommand being timed: "python3.9 server_energy.py 0 909"', '\tUser time (seconds): 6.66', '\tSystem time (seconds): 0.81', '\tPercent of CPU this job got: 87%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.54', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80652', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 15966', '\tVoluntary context switches: 63', '\tInvoluntary context switches: 113', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0', 'PowerTOP outputing using base filename log/powertop_rpi_2025-01-17_01-31-08.csv']
2025-01-17 01:31:42,583 - DEBUG - All values from powertop for client: 1       532 mW  
18     1.97 mW  
37      574 uW  
Name: 7, dtype: object
2025-01-17 01:31:42,583 - DEBUG - Energy client: 3.9770073600000004
2025-01-17 01:31:43,916 - DEBUG - All values from powertop for server: 1       535 mW  
33      902 uW  
38      710 uW  
Name: 7, dtype: object
2025-01-17 01:31:43,916 - DEBUG - Energy server: 3.9816610399999997
