2025-01-16 23:31:00,291 - INFO - Finished! Total sfe time: 10.468599081039429 
2025-01-16 23:31:00,292 - DEBUG - 692,server, Parsed server ram usage: 80624
2025-01-16 23:31:00,292 - DEBUG - 692,client, Parsed client ram usage: 80832
2025-01-16 23:31:21,413 - DEBUG - client all values : ['modprobe cpufreq_stats failedLoaded 0 prior measurements', 'RAPL device for cpu 0', 'RAPL device for cpu 0', 'Devfreq not enabled', 'glob returned GLOB_ABORTED', 'Preparing to take measurements', 'Taking 1 measurement(s) for a duration of 11 second(s) each.', '2024-12-19 03:28:47,277 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.1.1:61002', '2024-12-19 03:28:47,281 - tno.mpc.communication.httphandlers - ERROR - Message not received.', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1061, in _wrap_create_connection', '    sock = await aiohappyeyeballs.start_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 103, in start_connection', '    raise first_exception', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 81, in start_connection', '    sock = await _connect_sock(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 165, in _connect_sock', '    await loop.sock_connect(sock, address)', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect', '    return await fut', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb', "    raise OSError(err, f'Connect call failed {address}')", "ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.2', 61001)", '', 'The above exception was the direct cause of the following exception:', '', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/tno/mpc/communication/httphandlers.py", line 193, in _send', '    async with self.session.post(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1355, in __aenter__', '    self._resp: _RetType = await self._coro', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 659, in _request', '    conn = await self._connector.connect(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 557, in connect', '    proto = await self._create_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1002, in _create_connection', '    _, proto = await self._create_direct_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1336, in _create_direct_connection', '    raise last_exc', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1305, in _create_direct_connection', '    transp, proto = await self._wrap_create_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1076, in _wrap_create_connection', '    raise client_error(req.connection_key, exc) from exc', "aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.2:61001 ssl:default [Connect call failed ('192.168.1.2', 61001)]", '2024-12-19 03:28:48,350 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', '2024-12-19 03:28:48,382 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', '2024-12-19 03:28:48,491 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', '2024-12-19 03:28:48,540 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', 'TP is  0.001', '2024-12-19 03:28:48,557 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', '2024-12-19 03:28:48,578 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-12-19 03:28:48,579 - tno.mpc.communication.httphandlers - INFO - Server 192.168.1.1:61002 shutdown', 'Total bytes received: 1930', 'Total messages received: 5', '2024-12-19 03:28:48,583 - tno.mpc.communication.httphandlers - INFO - Client 192.168.1.2:61001 shutdown', 'Total bytes sent: 766', 'Total messages sent: 5', '2024-12-19 03:28:48,584 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 766', 'Total messages sent: 5', 'Total bytes received: 1930', 'Total messages received: 5', '\tCommand being timed: "python3.9 server_energy.py 1 692"', '\tUser time (seconds): 6.60', '\tSystem time (seconds): 0.79', '\tPercent of CPU this job got: 86%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.56', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80700', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 16071', '\tVoluntary context switches: 71', '\tInvoluntary context switches: 247', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0', 'PowerTOP outputing using base filename log/powertop_rpi_2025-01-16_23-30-49.csv']
2025-01-16 23:31:21,414 - DEBUG - server all values : ['modprobe cpufreq_stats failedLoaded 0 prior measurements', 'RAPL device for cpu 0', 'RAPL device for cpu 0', 'Devfreq not enabled', 'glob returned GLOB_ABORTED', 'Preparing to take measurements', 'Taking 1 measurement(s) for a duration of 11 second(s) each.', '2024-12-19 03:29:24,708 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.1.2:61001', '2024-12-19 03:29:25,686 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', '2024-12-19 03:29:25,801 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', '2024-12-19 03:29:25,827 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', '2024-12-19 03:29:25,896 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', 'TP is  0.001', '2024-12-19 03:29:25,941 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', '2024-12-19 03:29:25,946 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-12-19 03:29:25,948 - tno.mpc.communication.httphandlers - INFO - Server 192.168.1.2:61001 shutdown', 'Total bytes received: 766', 'Total messages received: 5', '2024-12-19 03:29:25,951 - tno.mpc.communication.httphandlers - INFO - Client 192.168.1.1:61002 shutdown', 'Total bytes sent: 1930', 'Total messages sent: 5', '2024-12-19 03:29:25,953 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 1930', 'Total messages sent: 5', 'Total bytes received: 766', 'Total messages received: 5', '\tCommand being timed: "python3.9 server_energy.py 0 692"', '\tUser time (seconds): 6.67', '\tSystem time (seconds): 0.80', '\tPercent of CPU this job got: 87%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.56', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80012', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 15955', '\tVoluntary context switches: 68', '\tInvoluntary context switches: 125', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0', 'PowerTOP outputing using base filename log/powertop_rpi_2025-01-16_23-30-49.csv']
2025-01-16 23:31:22,804 - DEBUG - All values from powertop for client: 1       240 mW  
11     8.87 mW  
19     4.78 mW  
Name: 7, dtype: object
2025-01-16 23:31:22,804 - DEBUG - Energy client: 1.87701
2025-01-16 23:31:24,131 - DEBUG - All values from powertop for server: 1       544 mW  
27     1.26 mW  
45      443 uW  
Name: 7, dtype: object
2025-01-16 23:31:24,131 - DEBUG - Energy server: 4.060030320000001
