2025-01-16 17:29:01,779 - INFO - Finished! Total sfe time: 5.319190263748169 
2025-01-16 17:29:01,780 - DEBUG - 21,server, Parsed server ram usage: 80192
2025-01-16 17:29:01,780 - DEBUG - 21,client, Parsed client ram usage: 80440
2025-01-16 17:29:13,326 - DEBUG - client all values : ['modprobe cpufreq_stats failedLoaded 0 prior measurements', 'RAPL device for cpu 0', 'RAPL device for cpu 0', 'Devfreq not enabled', 'glob returned GLOB_ABORTED', 'Preparing to take measurements', 'Taking 1 measurement(s) for a duration of 6 second(s) each.', '2024-12-18 21:26:44,974 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.1.1:61002', '2024-12-18 21:26:44,975 - tno.mpc.communication.httphandlers - ERROR - Message not received.', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1061, in _wrap_create_connection', '    sock = await aiohappyeyeballs.start_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 103, in start_connection', '    raise first_exception', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 81, in start_connection', '    sock = await _connect_sock(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 165, in _connect_sock', '    await loop.sock_connect(sock, address)', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect', '    return await fut', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb', "    raise OSError(err, f'Connect call failed {address}')", "ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.2', 61001)", '', 'The above exception was the direct cause of the following exception:', '', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/tno/mpc/communication/httphandlers.py", line 193, in _send', '    async with self.session.post(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1355, in __aenter__', '    self._resp: _RetType = await self._coro', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 659, in _request', '    conn = await self._connector.connect(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 557, in connect', '    proto = await self._create_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1002, in _create_connection', '    _, proto = await self._create_direct_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1336, in _create_direct_connection', '    raise last_exc', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1305, in _create_direct_connection', '    transp, proto = await self._wrap_create_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1076, in _wrap_create_connection', '    raise client_error(req.connection_key, exc) from exc', "aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.2:61001 ssl:default [Connect call failed ('192.168.1.2', 61001)]", '2024-12-18 21:26:46,014 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', '2024-12-18 21:26:46,032 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', '2024-12-18 21:26:46,077 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', '2024-12-18 21:26:46,104 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', 'TP is  0.001', '2024-12-18 21:26:46,114 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.2:61001', '2024-12-18 21:26:46,126 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-12-18 21:26:46,127 - tno.mpc.communication.httphandlers - INFO - Server 192.168.1.1:61002 shutdown', 'Total bytes received: 1930', 'Total messages received: 5', '2024-12-18 21:26:46,129 - tno.mpc.communication.httphandlers - INFO - Client 192.168.1.2:61001 shutdown', 'Total bytes sent: 766', 'Total messages sent: 5', '2024-12-18 21:26:46,130 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 766', 'Total messages sent: 5', 'Total bytes received: 1930', 'Total messages received: 5', '\tCommand being timed: "python3.9 server_energy.py 1 21"', '\tUser time (seconds): 3.71', '\tSystem time (seconds): 0.46', '\tPercent of CPU this job got: 79%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:05.23', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 81080', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 16080', '\tVoluntary context switches: 74', '\tInvoluntary context switches: 76', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0', 'PowerTOP outputing using base filename log/powertop_rpi_2025-01-16_17-28-56.csv']
2025-01-16 17:29:13,326 - DEBUG - server all values : ['modprobe cpufreq_stats failedLoaded 0 prior measurements', 'RAPL device for cpu 0', 'RAPL device for cpu 0', 'Devfreq not enabled', 'glob returned GLOB_ABORTED', 'Preparing to take measurements', 'Taking 1 measurement(s) for a duration of 6 second(s) each.', '2024-12-18 21:27:22,238 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.1.2:61001', '2024-12-18 21:27:23,241 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', '2024-12-18 21:27:23,302 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', '2024-12-18 21:27:23,317 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', '2024-12-18 21:27:23,343 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', 'TP is  0.001', '2024-12-18 21:27:23,369 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.1.1:61002', '2024-12-18 21:27:23,371 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-12-18 21:27:23,372 - tno.mpc.communication.httphandlers - INFO - Server 192.168.1.2:61001 shutdown', 'Total bytes received: 766', 'Total messages received: 5', '2024-12-18 21:27:23,374 - tno.mpc.communication.httphandlers - INFO - Client 192.168.1.1:61002 shutdown', 'Total bytes sent: 1930', 'Total messages sent: 5', '2024-12-18 21:27:23,375 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 1930', 'Total messages sent: 5', 'Total bytes received: 766', 'Total messages received: 5', '\tCommand being timed: "python3.9 server_energy.py 0 21"', '\tUser time (seconds): 3.75', '\tSystem time (seconds): 0.40', '\tPercent of CPU this job got: 79%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:05.21', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80364', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 15952', '\tVoluntary context switches: 56', '\tInvoluntary context switches: 254', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0', 'PowerTOP outputing using base filename log/powertop_rpi_2025-01-16_17-28-56.csv']
2025-01-16 17:29:14,164 - DEBUG - All values from powertop for client: 1       404 mW  
10     16.1 mW  
16     12.3 mW  
Name: 7, dtype: object
2025-01-16 17:29:14,164 - DEBUG - Energy client: 1.963096
2025-01-16 17:29:14,891 - DEBUG - All values from powertop for server: 1       385 mW  
11     15.6 mW  
Name: 7, dtype: object
2025-01-16 17:29:14,891 - DEBUG - Energy server: 1.8147179999999998
