2024-10-06 17:40:17,365 - INFO - Finished! Total sfe time: 10.512897491455078 
2024-10-06 17:40:17,365 - DEBUG - Host 192.168.0.101: exit code 0, output ['kamil123', '2024-10-06 16:48:22,199 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.101:61001', '2024-10-06 16:48:23,065 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 16:48:23,136 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 16:48:23,170 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 16:48:23,210 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', 'By 97 success.', '2024-10-06 16:48:23,255 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 16:48:23,260 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-06 16:48:23,262 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.101:61001 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-06 16:48:23,266 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.102:61002 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-06 16:48:23,267 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 0 97"', '\tUser time (seconds): 6.59', '\tSystem time (seconds): 0.56', '\tPercent of CPU this job got: 88%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.08', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 79768', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 15899', '\tVoluntary context switches: 49', '\tInvoluntary context switches: 192', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0'], error []
2024-10-06 17:40:17,365 - DEBUG - Host 192.168.0.102: exit code 0, output ['kamil123', '2024-10-06 16:48:21,870 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.102:61002', '2024-10-06 16:48:21,879 - tno.mpc.communication.httphandlers - ERROR - Message not received.', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1061, in _wrap_create_connection', '    sock = await aiohappyeyeballs.start_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 103, in start_connection', '    raise first_exception', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 81, in start_connection', '    sock = await _connect_sock(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 165, in _connect_sock', '    await loop.sock_connect(sock, address)', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect', '    return await fut', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb', "    raise OSError(err, f'Connect call failed {address}')", "ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.101', 61001)", '', 'The above exception was the direct cause of the following exception:', '', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/tno/mpc/communication/httphandlers.py", line 193, in _send', '    async with self.session.post(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1355, in __aenter__', '    self._resp: _RetType = await self._coro', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 659, in _request', '    conn = await self._connector.connect(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 557, in connect', '    proto = await self._create_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1002, in _create_connection', '    _, proto = await self._create_direct_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1336, in _create_direct_connection', '    raise last_exc', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1305, in _create_direct_connection', '    transp, proto = await self._wrap_create_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1076, in _wrap_create_connection', '    raise client_error(req.connection_key, exc) from exc', "aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.101:61001 ssl:default [Connect call failed ('192.168.0.101', 61001)]", '2024-10-06 16:48:22,954 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 16:48:22,990 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 16:48:23,023 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 16:48:23,077 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 16:48:23,095 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 16:48:23,117 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-06 16:48:23,119 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.102:61002 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-06 16:48:23,123 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.101:61001 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-06 16:48:23,125 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 1 97"', '\tUser time (seconds): 6.48', '\tSystem time (seconds): 0.67', '\tPercent of CPU this job got: 86%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.25', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80376', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 16016', '\tVoluntary context switches: 53', '\tInvoluntary context switches: 195', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0'], error []
2024-10-06 17:40:17,365 - DEBUG - 97,server, Parsed server ram usage: {'Command being timed': '"python3 server_energy.py 0 97"', 'User time (seconds)': '6.59', 'System time (seconds)': '0.56', 'Percent of CPU this job got': '88%', 'Elapsed (wall clock) time (h:mm:ss or m:ss)': '0:08.08', 'Average shared text size (kbytes)': '0', 'Average unshared data size (kbytes)': '0', 'Average stack size (kbytes)': '0', 'Average total size (kbytes)': '0', 'Maximum resident set size (kbytes)': '79768', 'Average resident set size (kbytes)': '0', 'Major (requiring I/O) page faults': '0', 'Minor (reclaiming a frame) page faults': '15899', 'Voluntary context switches': '49', 'Involuntary context switches': '192', 'Swaps': '0', 'File system inputs': '0', 'File system outputs': '0', 'Socket messages sent': '0', 'Socket messages received': '0', 'Signals delivered': '0', 'Page size (bytes)': '4096', 'Exit status': '0'}
2024-10-06 17:40:17,365 - DEBUG - 97,client, Parsed client ram usage: {'Command being timed': '"python3 server_energy.py 1 97"', 'User time (seconds)': '6.48', 'System time (seconds)': '0.67', 'Percent of CPU this job got': '86%', 'Elapsed (wall clock) time (h:mm:ss or m:ss)': '0:08.25', 'Average shared text size (kbytes)': '0', 'Average unshared data size (kbytes)': '0', 'Average stack size (kbytes)': '0', 'Average total size (kbytes)': '0', 'Maximum resident set size (kbytes)': '80376', 'Average resident set size (kbytes)': '0', 'Major (requiring I/O) page faults': '0', 'Minor (reclaiming a frame) page faults': '16016', 'Voluntary context switches': '53', 'Involuntary context switches': '195', 'Swaps': '0', 'File system inputs': '0', 'File system outputs': '0', 'Socket messages sent': '0', 'Socket messages received': '0', 'Signals delivered': '0', 'Page size (bytes)': '4096', 'Exit status': '0'}
2024-10-06 17:40:36,080 - DEBUG - Host 192.168.0.101: exit code None, output ['kamil123', 'modprobe cpufreq_stats failedLoaded 0 prior measurements', 'RAPL device for cpu 0', 'RAPL device for cpu 0', 'Devfreq not enabled', 'glob returned GLOB_ABORTED', 'Preparing to take measurements', 'Taking 1 measurement(s) for a duration of 11 second(s) each.', '2024-10-06 16:48:33,020 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.101:61001', '2024-10-06 16:48:34,064 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 16:48:34,143 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 16:48:34,178 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 16:48:34,216 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', 'By 97 success.', '2024-10-06 16:48:34,268 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.102:61002', '2024-10-06 16:48:34,273 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-06 16:48:34,275 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.101:61001 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-06 16:48:34,278 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.102:61002 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-06 16:48:34,279 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 0 97"', '\tUser time (seconds): 6.79', '\tSystem time (seconds): 0.72', '\tPercent of CPU this job got: 87%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.63', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80384', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 15902', '\tVoluntary context switches: 43', '\tInvoluntary context switches: 210', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0'], error []
2024-10-06 17:40:36,080 - DEBUG - Host 192.168.0.102: exit code 0, output ['kamil123', 'modprobe cpufreq_stats failedLoaded 0 prior measurements', 'RAPL device for cpu 0', 'RAPL device for cpu 0', 'Devfreq not enabled', 'glob returned GLOB_ABORTED', 'Preparing to take measurements', 'Taking 1 measurement(s) for a duration of 11 second(s) each.', '2024-10-06 16:48:32,850 - tno.mpc.communication.httphandlers - INFO - Serving on 192.168.0.102:61002', '2024-10-06 16:48:32,872 - tno.mpc.communication.httphandlers - ERROR - Message not received.', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1061, in _wrap_create_connection', '    sock = await aiohappyeyeballs.start_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 103, in start_connection', '    raise first_exception', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 81, in start_connection', '    sock = await _connect_sock(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 165, in _connect_sock', '    await loop.sock_connect(sock, address)', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect', '    return await fut', '  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb', "    raise OSError(err, f'Connect call failed {address}')", "ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.101', 61001)", '', 'The above exception was the direct cause of the following exception:', '', 'Traceback (most recent call last):', '  File "/home/kamil/.local/lib/python3.9/site-packages/tno/mpc/communication/httphandlers.py", line 193, in _send', '    async with self.session.post(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1355, in __aenter__', '    self._resp: _RetType = await self._coro', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/client.py", line 659, in _request', '    conn = await self._connector.connect(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 557, in connect', '    proto = await self._create_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1002, in _create_connection', '    _, proto = await self._create_direct_connection(req, traces, timeout)', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1336, in _create_direct_connection', '    raise last_exc', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1305, in _create_direct_connection', '    transp, proto = await self._wrap_create_connection(', '  File "/home/kamil/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1076, in _wrap_create_connection', '    raise client_error(req.connection_key, exc) from exc', "aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.101:61001 ssl:default [Connect call failed ('192.168.0.101', 61001)]", '2024-10-06 16:48:33,959 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 16:48:33,997 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 16:48:34,032 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 16:48:34,085 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 16:48:34,104 - tno.mpc.communication.httphandlers - INFO - Received message from 192.168.0.101:61001', '2024-10-06 16:48:34,131 - tno.mpc.communication.httphandlers - INFO - HTTPServer: Shutting down server task', '2024-10-06 16:48:34,132 - tno.mpc.communication.httphandlers - INFO - Server 192.168.0.102:61002 shutdown', 'Total bytes received: 775', 'Total messages received: 5', '2024-10-06 16:48:34,135 - tno.mpc.communication.httphandlers - INFO - Client 192.168.0.101:61001 shutdown', 'Total bytes sent: 775', 'Total messages sent: 5', '2024-10-06 16:48:34,136 - tno.mpc.communication.pool - INFO - Pool shutdown.', 'Total bytes sent: 775', 'Total messages sent: 5', 'Total bytes received: 775', 'Total messages received: 5', '\tCommand being timed: "python3 server_energy.py 1 97"', '\tUser time (seconds): 6.72', '\tSystem time (seconds): 0.79', '\tPercent of CPU this job got: 86%', '\tElapsed (wall clock) time (h:mm:ss or m:ss): 0:08.64', '\tAverage shared text size (kbytes): 0', '\tAverage unshared data size (kbytes): 0', '\tAverage stack size (kbytes): 0', '\tAverage total size (kbytes): 0', '\tMaximum resident set size (kbytes): 80344', '\tAverage resident set size (kbytes): 0', '\tMajor (requiring I/O) page faults: 0', '\tMinor (reclaiming a frame) page faults: 16015', '\tVoluntary context switches: 55', '\tInvoluntary context switches: 203', '\tSwaps: 0', '\tFile system inputs: 0', '\tFile system outputs: 0', '\tSocket messages sent: 0', '\tSocket messages received: 0', '\tSignals delivered: 0', '\tPage size (bytes): 4096', '\tExit status: 0', 'PowerTOP outputing using base filename log/powertop_2024-10-06_17-40-06.csv'], error []
2024-10-06 17:40:37,427 - DEBUG - All values from powertop for client: 1       563 mW  
20     1.64 mW  
Name: 7, dtype: object
2024-10-06 17:40:37,427 - DEBUG - Energy client: 4.2235072
2024-10-06 17:40:38,709 - DEBUG - All values from powertop for server: 1       545 mW  
29     1.27 mW  
Name: 7, dtype: object
2024-10-06 17:40:38,709 - DEBUG - Energy server: 4.1461893000000005
